FROM node:22-alpine AS build
WORKDIR /app
COPY frontend/webapp/package*.json ./
RUN npm install --no-audit --no-fund
COPY frontend/webapp .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
